# Generated by Django 4.2.4 on 2023-09-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('shirt_number', models.IntegerField(blank=True, default=0, null=True)),
                ('salary', models.IntegerField(blank=True, default=0, null=True)),
                ('appearance', models.IntegerField(blank=True, default=0, null=True)),
                ('goals', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
