# Generated by Django 4.2.4 on 2023-09-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('midfield', 'midfield')], default=True, max_length=30),
            preserve_default=False,
        ),
    ]
