# Generated by Django 4.2.4 on 2023-09-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='strong_foot',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('First Team', 'First Team'), ('Second Team', 'Second Team')], default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Goal Keeper', 'Goal Keeper'), ('Defender', 'Defender'), ('Midfield', 'Midfield'), ('Striker', 'Striker'), ('Winger', 'Winger')], max_length=30),
        ),
    ]
