# Generated by Django 4.2.4 on 2023-09-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_player_strong_foot_player_team_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.FileField(default=True, max_length=250, upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Goal Keeper', 'Goal Keeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Striker', 'Striker'), ('Winger', 'Winger')], max_length=30),
        ),
    ]
