# Generated by Django 4.2.4 on 2023-09-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_player_image_alter_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='image',
        ),
        migrations.AddField(
            model_name='player',
            name='player_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='club/'),
        ),
    ]
