# Generated by Django 4.2.4 on 2023-09-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_remove_player_image_player_player_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_pic', models.FileField(default=None, max_length=250, null=True, upload_to='club/')),
            ],
        ),
    ]
